### ISSUE TITLE
Retrieving images from queries

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [jaraco/wolframalpha#1]
Is it possible to retrieve images from queries? Example graphs, knot images, processed images? If not, do you plan to include such functionality?

**Comment by jaraco** [comment]
I don't believe so. The library was originally created for an IRC bot. I don't have any plans for this library, but I welcome outside contribution.

**Comment by The-Penultimate-Defenestrator** [comment]
Ok. I'm not really interested in developing it myself right now. I'll definately consider it for a future project.
