### ISSUE TITLE
NameError: name 'do_something_with' is not defined

### ISSUE THREAD

**Issue by pythongiant** [jaraco/wolframalpha#10]
Hi Here is my code
`import wolframalpha`
`client = wolframalpha.Client("5L4TR5-3QRQ88JWA3")`
`res = client.query('temperature in Washington, DC on October 3, 2012')`
`for pod in res.pods:`
`          do_something_with(pod)`
`for pod in res.pods:`
`           for sub in pod.subpods:`
`              print(sub.text)`
`print(next(res.results).text)`

and I have an error
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    do_something_with(pod)
NameError: name 'do_something_with' is not defined
`

**Comment by jaraco** [comment]
do_something_with is a stand-in for your code. Just delete that for loop.

**Comment by pythongiant** [comment]
thnx I just found out that
