### ISSUE TITLE
not linking to images some[/all ]times

### ISSUE THREAD

**Issue by j-j-v** [jaraco/wolframalpha#17]
thanks for this! very cool.

is it *possible* to link when i at least specify "image" or "visual representation" etc in a query? e.g ".wolframalpha regular tetrahedron image" giving the link to the output?  detect images & link to them? haven't experimented a lot, maybe it usually does. thanks

**Comment by jaraco** [comment]
I haven't used this library or the API recently, so I don't know the answer. I welcome experimentation and contribution. Don't hesitate to let us know what you've tried and what you find.
