### ISSUE TITLE
Add async support

### ISSUE THREAD

**Issue by denizsincar29** [jaraco/wolframalpha#30]
Hello! How to use this package asynchronously? I do an asynchronous telegram bot that use wolfram alpha api to get question results.

**Comment by Muhammadyusuf96** [comment]
same, le dot

**Comment by jaraco** [comment]
I don't believe this library has any async support. It was written before async was a thing in Python. I welcome contributions to add async support.

**Comment by jaraco** [comment]
In v5.1.0, `client.aquery` should work as an async call. Give it a try and let me know how it works.
